ProductName: "Spinat"
ProductDescription: "Aus dem eigenen Anbau."
Pricing:
  #0 = pro Gramm, 1 = pro Stück
  Type: 0
  GrammsPerUnit: 100
  PricePerUnit: 1.49
Calibration: 
  Offset: [41308, -239592, -8747, 26511]
  Slope: [-0.004746168, 0.004798805, -0.004741381, 0.004679427]
  GlobalOffset: 1924.9