ProductName: "Trauben2"
ProductDescription: "Aus dem eigenen Anbau."
Pricing:
  #0 = pro Gramm, 1 = pro Stück
  Type: 0
  GrammsPerUnit: 100
  PricePerUnit: 1.49
Calibration: 
  Offset: [-63214.1, 186820.6, 475.1, 8388607.0]
  Slope: [-1.20699E-03, 1.06272E-03, -1.10287E-03, 0]
  GlobalOffset: 0
