ProductName: "Trauben3"
ProductDescription: "Aus dem eigenen Anbau."
Pricing:
  #0 = pro Gramm, 1 = pro Stück
  Type: 0
  GrammsPerUnit: 100
  PricePerUnit: 1.49
Calibration: 
  Offset: [54148.9, 140098.6, -147084.4, 155639.7]
  Slope: [-4.463E-03, 4.501E-03, -4.461E-03, 4.465E-03]
  GlobalOffset: 1913.963
  DisplayRounding: 1
